// WARNING!!! DO NOT EDIT - FILE GENERATED BY APPLETGEN
#ifndef _FLASHAPPLETCODE_H
#define _FLASHAPPLETCODE_H

#include <stdint.h>

typedef struct
{
    uint8_t code[2248];
} FlashAppletCode;

#endif // _FLASHAPPLETCODE_H
